@startuml


title  База данных
header Носаченко А.
footer \n Схема таблиц

skinparam defaultFontName VL Gothic


' = = = = = = = =
' = = = = = = = =
' = = = = = = = =


namespace MS_Films {

class Films
{
  + <font color="gold"      >serial_   id;

  - text___   name_ru;

  - text___   name_en;

  + <font color="lightgreen">integer   id_country;

  + integer   year;

  + text___   age_rating;

  - integer   rating;

  + integer   duration;

  + text___   image_path;
}

class Countries
{
  + <font color="gold"      >serial_   id;

  + text___   name_ru;

  + text___   name_en;
}

class Film_genres
{
  + <font color="gold"      >serial_   id;

  + <font color="lightgreen">integer   id_film;

  + <font color="lightgreen">integer   id_genre;
}

class Genres
{
  + <font color="gold"      >serial_   id;

  + text___   name_ru;

  + text___   name_en;
}

class Film_members
{
  + <font color="gold"      >serial_   id;

  + <font color="lightgreen">integer   id_film;

  + <font color="lightgreen">integer   id_member;

  + <font color="lightgreen">integer   id_profession;
}

class Members
{
  + <font color="gold"      >serial_   id;

  - text___   name_ru;

  - text___   name_en;

  + text___   text;

  + text___   image_path;
}

class Professions
{
  + <font color="gold"      >serial_   id;

  + text___   name;
}

}


' = = = = = = = =
' = = = MiS = = =
' = = = = = = = =


namespace MS_Rating {

class Rating_films
{
  + <font color="gold"      >serial_   id;

  + <font color="lightblue" >integer   id_film;

  + integer   count;

  + integer   rating_film;

  + integer   rating_current;
}

class Rating_users
{
  + <font color="gold"      >serial_   id;

  + <font color="lightblue" >integer   id_film;

  + <font color="lightblue" >integer   id_user;

  + integer   rating;
}

}


' = = = = = = = =
' = = = MiS = = =
' = = = = = = = =


namespace MS_Film_info {

class Film_info
{
  + <font color="gold"      >serial_   id;

  + <font color="lightblue" >integer   id_film;

  + text___   text;

  + text___   trailer_link;
}

}


' = = = = = = = =
' = = = MiS = = =
' = = = = = = = =


namespace MS_Profiles {

class Profiles
{
  + <font color="gold"      >serial_   id;

  + <font color="lightblue" >integer   id_user;

  + text___   profile_name;

  - text___   image_path;
}

class Comments
{
  + <font color="gold"      >serial_   id;

  + <font color="lightblue" >integer   id_film;

  + <font color="lightgreen">integer   id_profile;

  - text___   title;

  + text___   text;

  + date___   date;

  - integer   prev_id;
}

}


' = = = = = = = =
' = = = MiS = = =
' = = = = = = = =


namespace MS_Users {

class Users
{
  + <font color="gold"      >serial_   id;

  + text___   email;

  + text___   password;

  + <font color="lightgreen">integer   id_role;
}

class Roles
{
  + <font color="gold"      >serial_   id;

  + text___   name;

  - text___   description;
}

}


' = = = = = = = =
' = = = = = = = =
' = = = = = = = =


Films        <|-- Countries
Film_genres  <|-- Films
Film_genres  <|-- Genres
Film_members <|-- Films
Film_members <|-- Members
Film_members <|-- Professions

Comments     <|-- Profiles
Users        <|-- Roles


' = = = = = = = =
' = = = RMQ = = =
' = = = = = = = =


Film_info    <--o Films
Rating_films <--o Films
Rating_users <--o Films
Rating_users <--o Users

Comments     <--o Films
Profiles     <--o Users


@enduml