
version: '0.1'

networks:
  local_net:
    driver: bridge

services:

  pg:
    image: postgres
    container_name: pg
    restart: always
    ports:
      - 5430:5432
#    volumes:
#      - ./postgres:/var/lib/postgresql/data
    networks:
      - local_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    expose:
      - '80'
    depends_on:
      - pg
    networks:
      - local_net

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/durables/:/var/lib/rabbitmq/
      - ./rabbitmq/logs/:/var/log/rabbitmq
    networks:
      - local_net

  users:
    build: ./_users
    container_name: users
    restart: on-failure
    depends_on:
      - pg
      - rabbitmq
    ports:
      - 12121:12121
    volumes:
      - ./_users:/root
    networks:
      - local_net

  profiles:
    build: ./_profiles
    container_name: profiles
    restart: on-failure
    depends_on:
      - pg
      - rabbitmq
    ports:
      - 12122:12122
    volumes:
      - ./_profiles:/root
    networks:
      - local_net

  films:
    build: ./_films
    container_name: films
    restart: on-failure
    depends_on:
      - pg
      - rabbitmq
    ports:
      - 12123:12123
    volumes:
      - ./_films:/root
    networks:
      - local_net

  film_info:
    build: ./_film_info
    container_name: film_info
    restart: on-failure
    depends_on:
      - pg
      - rabbitmq
    ports:
      - 12124:12124
    volumes:
      - ./_film_info:/root
    networks:
      - local_net

  rating:
    build: ./_rating
    container_name: rating
    restart: on-failure
    depends_on:
      - pg
      - rabbitmq
    ports:
      - 12125:12125
    volumes:
      - ./_rating:/root
    networks:
      - local_net
